config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets do
      collection do
          post :confirm
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :content, presence: true, length: { in: 1..140 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :get_tweet, only: [:edit, :update]
    
    def index
        #一覧画面なのでデータを全て取得し、ビューに渡す
        @tweets=Tweet.all
    end
    
    
    def new
        #モデルのインスタンスをビューに渡す
        @tweet=Tweet.new
        
        if params[:back]
         @tweet = Tweet.new(tweet_params)
        else
         @tweet = Tweet.new
        end
    end
    
    def create
        @tweet=Tweet.new(tweet_params)
        
        if @tweet.save
            redirect_to tweets_path
        else 
            render 'new'
        end
    end
    
    def edit
        #編集するためにはまず編集したいツイートを取得する必要がある
        #idを利用して値を取得する際はfindメソッドが使用でき、idはパラメーターとして送られてくる
        get_tweet
    end
    
    def update
        #更新するツイートを取得
        get_tweet
        
        if @tweet.update(tweet_params) 
            redirect_to tweets_path
        else
            render 'edit'
        end
    end
    
    def destroy
        (get_tweet).destroy
        redirect_to tweets_path
    end
    
    def confirm
        @tweet=Tweet.new(tweet_params)
        if @tweet.invalid?
            render :new
        end
    end
    
    private
    def tweet_params
        #newで入力された値をparamsで取得
        params.require(:tweet).permit(:content)
    end
    
    def get_tweet
        @tweet=Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_tweets_path
        elsif action_name == 'edit'
            tweet_path
        end
    end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
　　<meta name="viewport" content="width=device-width"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
     <div class="container-fluid">
      <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Twitter</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
       </button>
      <!--   <a class="navbar-brand" href="#">Twitter</a> -->
       </div>
      <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a class="glyphicon glyphicon-home" href="https://phase2-final-task-aaachanzu09-1.c9users.io/tweets">ホーム</a></li></span>
        <li><a class="glyphicon glyphicon-flash" href="">モーメント</a></li>
        <li><a class="glyphicon glyphicon-bell" href="">通知</a></li>
        <li><a class="glyphicon glyphicon-envelope" href="">メッセージ</a></li>
      </ul>
      <div class="navbar-right">
        <a class="navbar-brand" href="#">
			<!--	　<img alt="Image" src="../../profile_image.JPG" style="height: 20px;"/> -->
			　</a>
      　<form class="navbar-form navbar-left" role="search">
				　<div class="form-group">
					　<input type="text" class="form-control" placeholder="キーワード検索">
				　  <button type="submit" class="btn btn-default"> 検索</button>
				　</div>
			　</form>
			　<button type="button" class="btn btn-default navbar-btn"><a href="https://phase2-final-task-aaachanzu09-1.c9users.io/tweets/new">ツイート</a></button>
			</div>
    </div>
  </div>
</nav>
<!--
    <div class="container">

      <header>
        <ul  class="row">
          <img src="../../130955-the-ultimate/png/home-1.png" class="home_image">
          <li class="col-md-1">ホーム</li>
          <li class="col-md-1">モーメント</li>
          <li class="col-md-1">通知</li>
          <li class="col-md-1">メッセージ</li>

          <li class="col-md-offset-6 col-md-1">キーワード検索</li>
          <button type="button" class="btn btn-info">ツイート</button>
        </ul>
      </header>
    </div>
-->
<!--このdivはasidemとarticleを囲む-->
    <div class="row">
      <aside class="col-md-3">
        <div class="position"><!--青と白両方含んだ四角全体を囲むdiv--> 
          <p class="profile"></p>
          <a class="navbar-brand profile_image" href="#">
          <div class="parant">
            <p class="profile1"><a href="">Marie</a></p>
            <ul class="table">
             <li class="table_cell"><a href="">ツイート</br> 10</a></li>
             <li class="table_cell"><a href="">フォロー</br> 53</a></li>
             <li class="table_cell"><a href="">フォロワー</br> 48</a></li>
            </ul>
          </div>
        </div>
      </aside>
      <article class="col-md-6 container">
      <%= yield %>
      </article>
    </div>
  </body>
</html> 
 

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true, url: choose_new_or_edit) do |form| %>
<% if @tweet.errors.any? %>
  <div id="error_explanation">
    <p><%= @tweet.errors.count %>件のエラーがあります</p>
  
    <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="tweet_content">
    <div class="input-group">
    	<span class="input-group-addon"><%= form.label :Tweet %></span>
    	<%= form.text_field :content,:class => 'form-control',:placeholder => "いまどうしてる？" %>
   </div>
  </div>
    <%= form.submit %>
  <% end %> 

app/views/tweets/confirm.html.erb
<h3>Confirmation</h3>

<%= form_with(model: @tweet,  local: true) do |form| %>
 <div class="input-group">
    	<span class="input-group-addon"><%= form.label :Tweet %></span>
    	<%= form.text_field :content,:class => 'form-control',:placeholder => "いまどうしてる？",:readonly => true %>
 </div>
      <%= form.submit  "Register" %>
<% end %>

<!--form_withで戻るボタンを作成して、パラメーターとして値をnewメソッドに送る-->
<div>
  <%= form_with(model: @tweet, url: new_tweet_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :content %>
    <%= form.submit "Back", name: 'back' %>
  <% end %>
</div>

app/views/tweets/edit.html.erb
<%= render 'form' %>

app/views/tweets/index.html.erb
<table class="table table-hover table-responsive">
    <% @tweets.each do | tweet | %>
      <tr>
        <td><a class="navbar-brand" href="#"></td>
        <td class="table_text"><%= tweet.content %></td>
        <td><%= link_to '編集', edit_tweet_path(tweet.id), class: "btn btn-mini btn-info" %></td>
        <td><%= link_to '削除', tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？' },class: "btn btn-mini btn-danger" %></td>
      </tr>
    <% end %>
</table>

app/views/tweets/new.html.erb
<%= render 'form' %>